"""Replace regions with categories

Revision ID: edfeb9bbe7ed
Revises: f6d467cb25ad
Create Date: 2024-01-31 21:44:32.731819

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "edfeb9bbe7ed"
down_revision = "f6d467cb25ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table("queue_region", "category")
    op.execute("ALTER INDEX pk_queue_region RENAME TO pk_category")
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_category_name"), ["name"], unique=False)

    # rename table and columns
    op.rename_table("player_region_trueskill", "player_category_trueskill")
    op.alter_column(
        table_name="player_category_trueskill",
        column_name="queue_region_id",
        new_column_name="category_id",
    )
    op.alter_column(
        table_name="player_category_trueskill",
        column_name="rated_trueskill_mu",
        new_column_name="mu",
    )
    op.alter_column(
        table_name="player_category_trueskill",
        column_name="rated_trueskill_sigma",
        new_column_name="sigma",
    )
    # add new "rank" column
    op.add_column(
        table_name="player_category_trueskill",
        column=sa.Column("rank", sa.Float(), nullable=False, server_default="0.0"),
    )
    # drop old keys and indexes
    op.drop_column(
        table_name="player_category_trueskill", column_name="unrated_trueskill_mu"
    )
    op.drop_column(
        table_name="player_category_trueskill", column_name="unrated_trueskill_sigma"
    )
    op.drop_constraint(
        table_name="player_category_trueskill",
        constraint_name=op.f("pk_player_region_trueskill"),
    )
    op.drop_index(
        table_name="player_category_trueskill",
        index_name=op.f("ix_player_region_trueskill_created_at"),
    )
    op.drop_index(
        table_name="player_category_trueskill",
        index_name=op.f("ix_player_region_trueskill_player_id"),
    )
    op.drop_index(
        table_name="player_category_trueskill",
        index_name=op.f("ix_player_region_trueskill_queue_region_id"),
    )
    op.drop_constraint(
        table_name="player_category_trueskill",
        constraint_name=op.f("fk_player_region_trueskill_player_id_player"),
    )
    op.drop_constraint(
        table_name="player_category_trueskill",
        constraint_name=op.f("fk_player_region_trueskill_queue_region_id_queue_region"),
    )
    # add new keys and indexes
    op.create_primary_key(
        constraint_name=op.f("pk_player_category_trueskill"),
        table_name="player_category_trueskill",
        columns=["id"],
    )
    op.create_foreign_key(
        constraint_name=op.f("fk_player_category_trueskill_category_id_category"),
        source_table="player_category_trueskill",
        referent_table="category",
        local_cols=["category_id"],
        remote_cols=["id"],
    )
    op.create_foreign_key(
        constraint_name=op.f("fk_player_category_trueskill_player_id_player"),
        source_table="player_category_trueskill",
        referent_table="player",
        local_cols=["player_id"],
        remote_cols=["id"],
    )

    op.alter_column(
        "finished_game",
        "queue_region_name",
        nullable=True,
        new_column_name="category_name",
    )
    op.drop_index(op.f("ix_finished_game_queue_region_name"))
    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        # batch_op.add_column(sa.Column("category_name", sa.String(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_finished_game_category_name"),
            ["category_name"],
            unique=False,
        )

    op.alter_column("queue", "queue_region_id", True, new_column_name="category_id")
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_index("ix_queue_queue_region_id")
        batch_op.create_index(
            batch_op.f("ix_queue_category_id"), ["category_id"], unique=False
        )
        batch_op.drop_constraint(
            "fk_queue_queue_region_id_queue_region", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_queue_category_id_category"),
            "category",
            ["category_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("queue_region_id", sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(
            batch_op.f("fk_queue_category_id_category"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_queue_queue_region_id_queue_region",
            "queue_region",
            ["queue_region_id"],
            ["id"],
        )
        batch_op.drop_index(batch_op.f("ix_queue_category_id"))
        batch_op.create_index(
            "ix_queue_queue_region_id", ["queue_region_id"], unique=False
        )
        batch_op.drop_column("category_id")

    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_finished_game_category_name"))
        batch_op.drop_column("category_name")

    op.create_table(
        "player_region_trueskill",
        sa.Column("player_id", sa.INTEGER(), nullable=False),
        sa.Column("queue_region_id", sa.VARCHAR(), nullable=False),
        sa.Column("rated_trueskill_mu", sa.FLOAT(), nullable=False),
        sa.Column("rated_trueskill_sigma", sa.FLOAT(), nullable=False),
        sa.Column("unrated_trueskill_mu", sa.FLOAT(), nullable=False),
        sa.Column("unrated_trueskill_sigma", sa.FLOAT(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
            name="fk_player_region_trueskill_player_id_player",
        ),
        sa.ForeignKeyConstraint(
            ["queue_region_id"],
            ["queue_region.id"],
            name="fk_player_region_trueskill_queue_region_id_queue_region",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_player_region_trueskill"),
    )
    with op.batch_alter_table("player_region_trueskill", schema=None) as batch_op:
        batch_op.create_index(
            "ix_player_region_trueskill_queue_region_id",
            ["queue_region_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_player_region_trueskill_player_id", ["player_id"], unique=False
        )
        batch_op.create_index(
            "ix_player_region_trueskill_created_at",
            ["created_at"],
            unique=False,
        )

    with op.batch_alter_table("player_category_trueskill", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_category_trueskill_player_id"))
        batch_op.drop_index(batch_op.f("ix_player_category_trueskill_created_at"))
        batch_op.drop_index(batch_op.f("ix_player_category_trueskill_category_id"))

    op.drop_table("player_category_trueskill")
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_category_name"))

    op.drop_table("category")
    # ### end Alembic commands ###
