"""Make role_id BigInt

Revision ID: 0da35d56fceb
Revises: 4aa167bcf1b8
Create Date: 2025-09-10 08:58:27.691866

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0da35d56fceb"
down_revision = "4aa167bcf1b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_role", schema=None) as batch_op:
        batch_op.alter_column(
            "role_id",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_role", schema=None) as batch_op:
        batch_op.alter_column(
            "role_id",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
